---
name: shared-workflows
version: 1.0.0
description: Shared GitHub Actions workflows for esp-idf-lib
targets:
  - esp32
  - esp32p4
  - esp8266
groups:
  - common
depends:
  - freertos
thread_safe: n/a
license: ISC
copyrights:
  - name: trombik
    year: 2025
