---
name: Build docs
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install package requirements
        run: |
          sudo apt update
          sudo apt-get install make doxygen

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: docs/requirements.txt

      - name: Install python packages
        run: |
          pip install -r docs/requirements.txt

      - name: Build the docs
        run: |
          make -C docs all
