---
name: Test build-docs.yml
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  # permissions required by build-docs.yml
  pages: write
  # permissions required by build-docs.yml
  id-token: write

jobs:
  build-docs:
    uses: ./.github/workflows/build-docs.yml

  build-docs-and-publish:
    uses: ./.github/workflows/build-docs.yml
    with:
      publish: true

  verify-build-docs-and-publish:
    runs-on: ubuntu-latest
    needs: build-docs-and-publish
    steps:
      - name: Fail if page_url is not defined
        if: ${{ ! needs.build-docs-and-publish.outputs.page_url }}
        run: |
          echo "::error title=Failed to publish::Requested build-docs.yml to build and publish HTML files, but page_url is not defined"
          exit 1
