---
name: Build docs

# This workflow builds docuemntation of a component and (optionally) publish
# the generated HTML files on GitHub Pages.

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        default: false
        description: |
          Publish generated HTML files on GitHub Pages when true. When false,
          the default, the workflow builds the documentation only.

          Before using this feature, configure the repository from which
          workflows call this workflow.

          Visit [Settings] > [Pages] (in the side bar at left) > [Source],
          and choose [GitHub Actions] as [Source] (under [Build and deployment]).
          Otherwise, the workflow fails.

          Next, call this workflow with permissions with

          * pages: write
          * id-token: write

          The calling workflow should look like:

          ---
          name: Publish HTML files on GitHub Pages
          on: push
          permissions:
            # required by actions/deploy-pages
            pages: write
            id-token: write
          jobs:
            publish:
              uses: esp-idf-lib/shared-workflows/.github/workflows/build-docs.yml@main
              with:
                publish: true

    outputs:
      page_url:
        description: |
          URL of the published Paegs when publish is true and the deployment is
          successful.
        value: ${{ jobs.deploy.outputs.page_url }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install package requirements
        run: |
          sudo apt update
          sudo apt-get install make doxygen

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: docs/requirements.txt

      - name: Install python packages
        run: |
          pip install -r docs/requirements.txt

      - name: Run doxygen
        # XXX use version 1.9.6. 1.9.8 is broken and the output is corrupted.
        # use the GitHub Action because, with packaged doxygen, version cannot
        # be chosen.
        # https://github.com/doxygen/doxygen/issues/11323
        uses: mattnotmitt/doxygen-action@v1.9.6
        with:
          working-directory: docs
          doxyfile-path: ./doxygen.conf

      - name: Build the docs
        # XXX using sudo is required because the previouse step, "Run doxygen"
        # runs as a different user. During the `make` execution, generated XML
        # file must be fixed before sphinx-build, using `sed`, resulting
        # "permission denied".
        run: |
          echo "breathe version: `breathe-apidoc --version`"
          echo "sphinx version:  `sphinx-build --version`"
          sudo make -C docs all

      - name: Upload HTML files as artifact
        if: ${{ inputs.publish }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html/

  deploy:
    if: ${{ inputs.publish }}
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
