---
name: Build docs
on:
  workflow_call:
    inputs:
      upload:
        description: Upload generated HTML files
        required: false
        type: boolean

    outputs:
      artifact-id:
        description: artifact-id of the uploaded HTML files.
        value: ${{ jobs.build.outputs.artifact-id }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install package requirements
        run: |
          sudo apt update
          sudo apt-get install make doxygen

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: docs/requirements.txt

      - name: Install python packages
        run: |
          pip install -r docs/requirements.txt

      - name: Build the docs
        run: |
          make -C docs all

      - name: Upload HTML files
        id: upload
        if: ${{ inputs.upload }}
        uses: actions/upload-artifact@v4
        with:
          name: html-gh-pages
          path: docs/_build/html
