---
name: Test build examples workflow
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    uses: ./.github/workflows/build-examples.yml
  build-docs:
    uses: ./.github/workflows/build-docs.yml
