---
name: style
on:
  workflow_call:
jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      result:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install requirements
        run: |
          pip install astyle

      - name: Validte sources with astyle
        run: |
          astyle --project --recursive '*.c,*.h'
          if git diff --exit-code; then
            echo "No difference"
          else
            echo "::error title=Style Error::The code does not follow our code style. Run: astyle --project --recursive '*.c,*.h' to format the code"
            exit 1
          fi
