---
name: Validate the component with staging ESP Component Registry
# This workflow validates the component with ESP Component Registry.

on:
  workflow_call:
    inputs:
      namespace:
        description: The namespace of the component.
        default: esp-idf-lib
        required: false
        type: string

      components:
        description: |
          Semicolon or new-line separated list of component_name:relative/path pairs.
          See `components` at https://github.com/espressif/upload-components-ci-action?tab=readme-ov-file#parameters
          for more details.

          An example for a single component repository:
          mycomponent: .

          Be sure to double-quote the value above in the YAML file:

          ```yaml
          validate-with-esp-component-registry:
            uses: ./.github/workflows/validate-with-esp-component-registry.yml
            with:
              components: "mycomponent: ."
          ```
        required: true
        type: string

jobs:
  validate-component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate the component with ESP Component Registry
        uses: espressif/upload-components-ci-action@v2
        with:
          namespace: ${{ inputs.namespace }}
          components: ${{ inputs.components }} .
          dry_run: true
