---
name: Validate the component with staging ESP Component Registry
# This workflow validates the component with ESP Component Registry.

on:
  workflow_call:
    secrets:
      api_token:
        required: true
    inputs:
      namespace:
        description: The namespace of the component.
        default: esp-idf-lib
        required: false
        type: string

      components:
        description: |
          Semicolon or new-line separated list of component_name:relative/path pairs.
          See `components` at https://github.com/espressif/upload-components-ci-action?tab=readme-ov-file#parameters
          for more details.

          An example for a single component repository named `mycomponent`:
          mycomponent:.

          Be sure to double-quote the value above in the YAML file:
        required: true
        type: string

jobs:
  validate-component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate the component with ESP Component Registry
        uses: espressif/upload-components-ci-action@v2
        with:
          namespace: ${{ inputs.namespace }}
          components: ${{ inputs.components }}
          api_token: ${{ secrets.api_token }}
          dry_run: true
